program: run.py
project: moseq-dtd-sweep-20250225
method: grid
parameters:
  k1:
    values: [24, 48] # [2,4,8,16,32,64,96,128,256]
  k2:
    values: [2,4,6,8,16,20]
  k3:
    values: [2,4,8,16,24,36,48,72,90]
command:
  - ${env}
  - ${interpreter}
  - ${program}
  - ${args}
  - "--data_path=/home/groups/swl1/eyz/data/moseq-drugs/syllable_binned_1min.npz"
  - "--mask_frac=0.2"
  - "--n_folds=1"
  - "--n_epochs=500"
  - "--output_dir=/scratch/users/eyz/tmp/"
  - "--wandb_project"
  - ${envvar:WANDB_PROJECT}